"""Init

Revision ID: 451718c478ba
Revises: 
Create Date: 2025-06-05 21:01:54.939048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451718c478ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('status', sa.Enum('READING', 'READ', 'POSTPONED', 'PLANNED', name='bookstatus'), nullable=True))
    op.drop_index('ix_books_external_id', table_name='books')
    op.create_index(op.f('ix_books_external_id'), 'books', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_external_id'), table_name='books')
    op.create_index('ix_books_external_id', 'books', ['external_id'], unique=1)
    op.drop_column('books', 'status')
    # ### end Alembic commands ###
